# Generated by Django 4.2.6 on 2023-11-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.CharField(default=22, max_length=250),
            preserve_default=False,
        ),
    ]
